### ISSUE TITLE
Publish this crate

### ISSUE THREAD

**Issue by virtualritz** [anderslanglands/colorspace-rs#3]
`cargo publish` – you can do it! ;)

I talked to the [`iced`](https://github.com/hecrj/iced) guys about supporting proper display of color widgets for their GUI crate and they are interested.

It would be nice to have as you could easily add e.g. a color picker or color ramp widget to an app in Rust then and not worry about getting display right.

So then I got bold and suggested they could use your crate over [`palette`](https://github.com/Ogeon/palette).

**Comment by anderslanglands** [comment]
Alright this one I will do this week :)

**Comment by anderslanglands** [comment]
Done :)
